apiVersion: v1
kind: PersistentVolumeClaim # Define a PersistentVolumeClaim
metadata:
  name: mssql-claim # Name of the PVC
spec:
  accessModes:
    - ReadWriteMany # Access mode for the volume
  resources:
    requests:
      storage: 200Mi # Requested storage size
